version: 1
jobs:
  compile:
    image: node
    script:
      - npm install truffle
      - npx truffle compile
  test:
    image: node
    script:
      - npm install truffle
      - npx truffle test
  hello:
    image: node
    script:
      - echo Hello world !
  run:
    image: node
    script:
      - truffle develop
      - truffle migrate
      - npm run dev
stages:
  - pipeline:
      jobs:
        - compile
        - test
        - hello
        - run
