version: 1
jobs:
  compile:
    image: node
    script:
      - npm install truffle
      #- npx truffle compile
  test:
    image: node
    script:
      - npm install truffle
      #- npx truffle test
  hello:
    image: node
    script:
      e echo Hello world !
stages:
  - pipeline:
      jobs:
        - compile
        - test
        - hello