version: 1
jobs:
  compile:
    image: node
    script:
      - npm install truffle
      - npx truffle compile
  test:
    image: node
    script:
      - npm install truffle
      - npx truffle test
  hello:
    image: node
    script:
      - echo Hello world !
  run:
    image: node
    type:
        name: ethereum/deploy
    script:
        - npm install
        - npx truffle migrate --network superblock --reset
stages:
  - build_and_test:
      jobs: 
        - compile
        - test
  - deploy:
      jobs:
        - run:
            when: manual
